from manim import *
# AUTO-GENERATED by converter — do not edit manually

class GeneratedScene(Scene):
    def construct(self):
        
        # --- title (0.0s → 2.5s)
        
        
        t_0 = Text("Limit Intuition").scale(1.1666666666666667)
        self.play(Write(t_0))
        self.wait(2.5)
        self.play(FadeOut(t_0))
        
        
        
        # --- def (2.5s → 5.5s)
        
        
        t_0 = Text("Definition of a limit.").scale(0.75)
        self.play(Write(t_0))
        self.wait(3.0)
        self.play(FadeOut(t_0))
        
        
        
        # --- example (5.5s → 9.5s)
        
        
        m_0 = MathTex(r"""f&#39;(x)=\lim_{h\to 0}\frac{f(x+h)-f(x)}{h}""")
        self.play(Write(m_0))
        self.wait(4.0)
        self.play(FadeOut(m_0))
        
        
        